Convert Request to Got
onetune/spotify-web-helper pull request #26
Opened 2017-06-01 21:58 UTC by itotallyrock

Everything on my system functioned properly.  My only concern is that [got](https://github.com/sindresorhus/got) v6 and later (we have v7) require node > 4.0.  We may need to express this in our own readme or add it to package.json engines field.

2017-06-01 22:06 UTC, JonnyBurger commented
Awesome!

We already require node >= 4.0.0 since v1.3.0. 

Will do a quick review in the next few days and then merge.

2017-06-01 22:13 UTC, JonnyBurger requested changes
Overall looks great! Thanks a lot!

2017-06-01 22:13 UTC, JonnyBurger commented on index.js
> +		}).then(request => {
Can you set `rejectUnauthorized` to `false` again here?
We took this property from `node-spotify-web-helper` and I guess there was a reason. I just want to make sure to not break stuff with this PR.

`got` should support this as well: https://github.com/sindresorhus/got/search?utf8=✓&q=rejectUnauthorized&type=

2017-06-01 22:13 UTC, JonnyBurger commented on index.js
> +		}).then(request => {
`request` would be named `response` more appropriately. The variables `request` and `response` are common in node and developers expect to be able to do certain things with these objects. This is a bit confusing.

2017-06-01 22:30 UTC, itotallyrock commented on index.js
> +		}).then(request => {
That was a simple mess up on my end, I made all the changes and then accidentally discarded them all and just typed it back up real quick, must've slipped by me.

2017-06-02 01:09 UTC, itotallyrock reviewed
Somehow I forgot to stage this change... it changed it but it never got commited.  Guess that is why we have code-review 😛

2017-06-02 17:31 UTC, JonnyBurger approved these changes

2017-06-02 17:31 UTC, merged

2017-06-02 17:32 UTC, JonnyBurger commented
Thanks a lot! Perfect.